# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(843, 606)
        self.button_box = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.button_box.setGeometry(QtCore.QRect(460, 560, 191, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.groupBox = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 261, 451))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 51, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 51, 20))
        self.label_2.setObjectName("label_2")
        self.node_width_slider = QtWidgets.QSlider(self.groupBox)
        self.node_width_slider.setGeometry(QtCore.QRect(80, 30, 160, 24))
        self.node_width_slider.setMinimum(20)
        self.node_width_slider.setMaximum(400)
        self.node_width_slider.setOrientation(QtCore.Qt.Horizontal)
        self.node_width_slider.setObjectName("node_width_slider")
        self.node_height_slider = QtWidgets.QSlider(self.groupBox)
        self.node_height_slider.setGeometry(QtCore.QRect(80, 60, 160, 24))
        self.node_height_slider.setMinimum(10)
        self.node_height_slider.setMaximum(200)
        self.node_height_slider.setOrientation(QtCore.Qt.Horizontal)
        self.node_height_slider.setObjectName("node_height_slider")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 61, 20))
        self.label_3.setObjectName("label_3")
        self.node_root_c_pb = QtWidgets.QPushButton(self.groupBox)
        self.node_root_c_pb.setGeometry(QtCore.QRect(150, 200, 61, 36))
        self.node_root_c_pb.setObjectName("node_root_c_pb")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 310, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(50, 360, 63, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(50, 410, 63, 20))
        self.label_7.setObjectName("label_7")
        self.node_atomic_c_pb = QtWidgets.QPushButton(self.groupBox)
        self.node_atomic_c_pb.setGeometry(QtCore.QRect(150, 250, 61, 36))
        self.node_atomic_c_pb.setObjectName("node_atomic_c_pb")
        self.node_composite_c_pb = QtWidgets.QPushButton(self.groupBox)
        self.node_composite_c_pb.setGeometry(QtCore.QRect(150, 300, 61, 36))
        self.node_composite_c_pb.setObjectName("node_composite_c_pb")
        self.node_schema_c_pb = QtWidgets.QPushButton(self.groupBox)
        self.node_schema_c_pb.setGeometry(QtCore.QRect(150, 350, 61, 36))
        self.node_schema_c_pb.setObjectName("node_schema_c_pb")
        self.node_say_c_pb = QtWidgets.QPushButton(self.groupBox)
        self.node_say_c_pb.setGeometry(QtCore.QRect(150, 400, 61, 36))
        self.node_say_c_pb.setObjectName("node_say_c_pb")
        self.node_border_cb = QtWidgets.QCheckBox(self.groupBox)
        self.node_border_cb.setGeometry(QtCore.QRect(20, 150, 94, 26))
        self.node_border_cb.setObjectName("node_border_cb")
        self.node_shadow_cb = QtWidgets.QCheckBox(self.groupBox)
        self.node_shadow_cb.setGeometry(QtCore.QRect(140, 150, 94, 26))
        self.node_shadow_cb.setObjectName("node_shadow_cb")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 81, 20))
        self.label_12.setObjectName("label_12")
        self.node_t_contrast_slider = QtWidgets.QSlider(self.groupBox)
        self.node_t_contrast_slider.setGeometry(QtCore.QRect(80, 100, 160, 24))
        self.node_t_contrast_slider.setMaximum(255)
        self.node_t_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.node_t_contrast_slider.setObjectName("node_t_contrast_slider")
        self.groupBox_2 = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 310, 261, 231))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(20, 30, 63, 20))
        self.label_22.setObjectName("label_22")
        self.edge_arrow_size_slider = QtWidgets.QSlider(self.groupBox_2)
        self.edge_arrow_size_slider.setGeometry(QtCore.QRect(80, 30, 160, 24))
        self.edge_arrow_size_slider.setMinimum(3)
        self.edge_arrow_size_slider.setMaximum(50)
        self.edge_arrow_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.edge_arrow_size_slider.setObjectName("edge_arrow_size_slider")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(50, 80, 63, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(50, 130, 63, 20))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(50, 180, 91, 20))
        self.label_25.setObjectName("label_25")
        self.edge_in_c_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.edge_in_c_pb.setGeometry(QtCore.QRect(150, 70, 51, 36))
        self.edge_in_c_pb.setObjectName("edge_in_c_pb")
        self.edge_follows_c_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.edge_follows_c_pb.setGeometry(QtCore.QRect(150, 120, 51, 36))
        self.edge_follows_c_pb.setObjectName("edge_follows_c_pb")
        self.edge_user_defined_c_pb = QtWidgets.QPushButton(self.groupBox_2)
        self.edge_user_defined_c_pb.setGeometry(QtCore.QRect(150, 170, 51, 36))
        self.edge_user_defined_c_pb.setObjectName("edge_user_defined_c_pb")
        self.groupBox_3 = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 70, 261, 231))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.graph_background_c_pb = QtWidgets.QPushButton(self.groupBox_3)
        self.graph_background_c_pb.setGeometry(QtCore.QRect(150, 30, 61, 36))
        self.graph_background_c_pb.setObjectName("graph_background_c_pb")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(50, 40, 81, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 81, 20))
        self.label_9.setObjectName("label_9")
        self.graph_h_spacing_slider = QtWidgets.QSlider(self.groupBox_3)
        self.graph_h_spacing_slider.setGeometry(QtCore.QRect(80, 120, 160, 24))
        self.graph_h_spacing_slider.setMinimum(20)
        self.graph_h_spacing_slider.setMaximum(600)
        self.graph_h_spacing_slider.setOrientation(QtCore.Qt.Horizontal)
        self.graph_h_spacing_slider.setObjectName("graph_h_spacing_slider")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.label_10.setObjectName("label_10")
        self.graph_gradient_slider = QtWidgets.QSlider(self.groupBox_3)
        self.graph_gradient_slider.setGeometry(QtCore.QRect(80, 80, 160, 24))
        self.graph_gradient_slider.setMinimum(100)
        self.graph_gradient_slider.setMaximum(200)
        self.graph_gradient_slider.setOrientation(QtCore.Qt.Horizontal)
        self.graph_gradient_slider.setObjectName("graph_gradient_slider")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.label_11.setObjectName("label_11")
        self.graph_v_spacing_slider = QtWidgets.QSlider(self.groupBox_3)
        self.graph_v_spacing_slider.setGeometry(QtCore.QRect(80, 160, 160, 24))
        self.graph_v_spacing_slider.setMinimum(20)
        self.graph_v_spacing_slider.setMaximum(300)
        self.graph_v_spacing_slider.setOrientation(QtCore.Qt.Horizontal)
        self.graph_v_spacing_slider.setObjectName("graph_v_spacing_slider")
        self.graph_hide_collapse_slider = QtWidgets.QSlider(self.groupBox_3)
        self.graph_hide_collapse_slider.setGeometry(QtCore.QRect(80, 200, 160, 24))
        self.graph_hide_collapse_slider.setMinimum(0)
        self.graph_hide_collapse_slider.setMaximum(255)
        self.graph_hide_collapse_slider.setOrientation(QtCore.Qt.Horizontal)
        self.graph_hide_collapse_slider.setObjectName("graph_hide_collapse_slider")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 61, 20))
        self.label_13.setObjectName("label_13")
        self.load_pb = QtWidgets.QPushButton(SettingsDialog)
        self.load_pb.setGeometry(QtCore.QRect(70, 20, 121, 36))
        self.load_pb.setObjectName("load_pb")
        self.save_pb = QtWidgets.QPushButton(SettingsDialog)
        self.save_pb.setGeometry(QtCore.QRect(210, 20, 121, 36))
        self.save_pb.setObjectName("save_pb")
        self.groupBox_4 = QtWidgets.QGroupBox(SettingsDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 70, 261, 401))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(40, 50, 91, 20))
        self.label_19.setObjectName("label_19")
        self.mp_code_comment_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_comment_c_pb.setGeometry(QtCore.QRect(160, 40, 61, 36))
        self.mp_code_comment_c_pb.setObjectName("mp_code_comment_c_pb")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(50, 100, 63, 20))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.mp_code_keyword_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_keyword_c_pb.setGeometry(QtCore.QRect(160, 90, 61, 36))
        self.mp_code_keyword_c_pb.setObjectName("mp_code_keyword_c_pb")
        self.mp_code_variable_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_variable_c_pb.setGeometry(QtCore.QRect(160, 140, 61, 36))
        self.mp_code_variable_c_pb.setObjectName("mp_code_variable_c_pb")
        self.mp_code_operator_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_operator_c_pb.setGeometry(QtCore.QRect(160, 240, 61, 36))
        self.mp_code_operator_c_pb.setObjectName("mp_code_operator_c_pb")
        self.mp_code_meta_symbol_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_meta_symbol_c_pb.setGeometry(QtCore.QRect(160, 340, 61, 36))
        self.mp_code_meta_symbol_c_pb.setObjectName("mp_code_meta_symbol_c_pb")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(40, 100, 91, 20))
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(40, 150, 91, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(40, 250, 91, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(40, 300, 101, 20))
        self.label_28.setObjectName("label_28")
        self.mp_code_quoted_text_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_quoted_text_c_pb.setGeometry(QtCore.QRect(160, 290, 61, 36))
        self.mp_code_quoted_text_c_pb.setObjectName("mp_code_quoted_text_c_pb")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(40, 350, 101, 20))
        self.label_29.setObjectName("label_29")
        self.mp_code_number_c_pb = QtWidgets.QPushButton(self.groupBox_4)
        self.mp_code_number_c_pb.setGeometry(QtCore.QRect(160, 190, 61, 36))
        self.mp_code_number_c_pb.setObjectName("mp_code_number_c_pb")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(40, 200, 91, 20))
        self.label_30.setObjectName("label_30")

        self.retranslateUi(SettingsDialog)
        self.button_box.accepted.connect(SettingsDialog.accept)
        self.button_box.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Graph Settings"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Nodes"))
        self.label.setText(_translate("SettingsDialog", "Width"))
        self.label_2.setText(_translate("SettingsDialog", "Height"))
        self.node_width_slider.setToolTip(_translate("SettingsDialog", "Node width"))
        self.node_height_slider.setToolTip(_translate("SettingsDialog", "Node height"))
        self.label_3.setText(_translate("SettingsDialog", "Root"))
        self.node_root_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.label_4.setText(_translate("SettingsDialog", "Atomic"))
        self.label_5.setText(_translate("SettingsDialog", "Composite"))
        self.label_6.setText(_translate("SettingsDialog", "Schema"))
        self.label_7.setText(_translate("SettingsDialog", "Say"))
        self.node_atomic_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.node_composite_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.node_schema_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.node_say_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.node_border_cb.setText(_translate("SettingsDialog", "Border"))
        self.node_shadow_cb.setText(_translate("SettingsDialog", "Shadow"))
        self.label_12.setText(_translate("SettingsDialog", "T Contrast"))
        self.node_t_contrast_slider.setToolTip(_translate("SettingsDialog", "Node text color contrast threshold"))
        self.groupBox_2.setTitle(_translate("SettingsDialog", "Edges"))
        self.label_22.setText(_translate("SettingsDialog", "Arrows"))
        self.edge_arrow_size_slider.setToolTip(_translate("SettingsDialog", "Arrow size"))
        self.label_23.setText(_translate("SettingsDialog", "In"))
        self.label_24.setText(_translate("SettingsDialog", "Follows"))
        self.label_25.setText(_translate("SettingsDialog", "User Defined"))
        self.edge_in_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.edge_follows_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.edge_user_defined_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.groupBox_3.setTitle(_translate("SettingsDialog", "Graph"))
        self.graph_background_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.label_8.setText(_translate("SettingsDialog", "Background"))
        self.label_9.setText(_translate("SettingsDialog", "H Spacing"))
        self.graph_h_spacing_slider.setToolTip(_translate("SettingsDialog", "Horizontal spacing between events"))
        self.label_10.setText(_translate("SettingsDialog", "Gradient"))
        self.graph_gradient_slider.setToolTip(_translate("SettingsDialog", "Color gradient"))
        self.label_11.setText(_translate("SettingsDialog", "V Spacing"))
        self.graph_v_spacing_slider.setToolTip(_translate("SettingsDialog", "Vertical spacing between events"))
        self.graph_hide_collapse_slider.setToolTip(_translate("SettingsDialog", "Opacity of hidden/collapsed events"))
        self.label_13.setText(_translate("SettingsDialog", "Hidden"))
        self.load_pb.setToolTip(_translate("SettingsDialog", "Open saved settings"))
        self.load_pb.setText(_translate("SettingsDialog", "Load settings..."))
        self.save_pb.setText(_translate("SettingsDialog", "Save settings..."))
        self.groupBox_4.setTitle(_translate("SettingsDialog", "MP Code"))
        self.label_19.setText(_translate("SettingsDialog", "Comments"))
        self.mp_code_comment_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.mp_code_keyword_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.mp_code_variable_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.mp_code_operator_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.mp_code_meta_symbol_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.label_21.setText(_translate("SettingsDialog", "Keywords"))
        self.label_26.setText(_translate("SettingsDialog", "Variables"))
        self.label_27.setText(_translate("SettingsDialog", "Operators"))
        self.label_28.setText(_translate("SettingsDialog", "Quoted text"))
        self.mp_code_quoted_text_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.label_29.setText(_translate("SettingsDialog", "Meta-Symbols"))
        self.mp_code_number_c_pb.setText(_translate("SettingsDialog", "Color"))
        self.label_30.setText(_translate("SettingsDialog", "Numbers"))

